---
- name: Update cache
  ansible.builtin.package:
    update_cache: true

- name: Install nginx
  ansible.builtin.package:
    name: nginx

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
