---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: community.general.opentelemetry
    callback_opentelemetry:
      enable_from_environment: ANSIBLE_OPENTELEMETRY_ENABLED
  env:
    ANSIBLE_OPENTELEMETRY_ENABLED: "true"
    OTEL_SERVICE_NAME: "Nginx CI"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://192.168.0.50:32015"
    OTEL_EXPORTER_OTLP_INSECURE: "true"
verifier:
  name: ansible
