---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: ansible_target
    pre_build_image: true
    inventory:
      host_vars:
        centos8:
          ansible_user: ansible
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
