---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Get info from Nginx running process
      ansible.builtin.command: systemctl status nginx
      register: nginx_status

    - name: Assert that nginx is up and running
      ansible.builtin.assert:
        that:
          - nginx_status is success
        success_msg: Nginx successfully installed and started
        fail_msg: The test validation failed, please check manually
