---
- name: Add desired user
  become: true
  ansible.builtin.user:
    name: admin

- name: Validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin ALL='
    line: '%admin ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
