---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Get root user info
      ansible.builtin.getent:
        database: passwd
        key: admin

    - name: Validate 1 user is found
      ansible.builtin.assert:
        that:
          - ansible_facts.getent_passwd | length == 1
        success_msg: The user was found
        fail_msg: The user was not found
